#! /usr/bin/sh

#author:rski
#email:rom.skiad@gmail.com
#filename:scrotum
#take a screenshot with escrotum and put it in a $YEAR/$MONTH folder
. ./lib/env
escrotum $1 -e "mkdir -p $SCREENCAPS_DIR && mv \$f $SCREENCAPS_DIR"
